server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mooc_meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    filters: log4j,wall,mergeStat
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:com/mooc/jiangzh/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:???ID??   1:????id  2:????id(IdWorker)  3:????ID(uuid)
    db-column-underline: false
    refresh-mapper: true


logging:
  config: classpath:logback.xml